In [2]:
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 데이터프레임 로드

In [4]:
# 경로복사 하세요.
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/sel_h_p.csv')

In [5]:
df

     지역명               규모구분    연도   월 분양가격(㎡)
0     서울                 전체  2015  10    5841
1     서울         전용면적 60㎡이하  2015  10    5652
2     서울   전용면적 60㎡초과 85㎡이하  2015  10    5882
3     서울  전용면적 85㎡초과 102㎡이하  2015  10    5721
4     서울        전용면적 102㎡초과  2015  10    5879
...   ..                ...   ...  ..     ...
4500  제주                 전체  2020   2    3955
4501  제주         전용면적 60㎡이하  2020   2    4039
4502  제주   전용면적 60㎡초과 85㎡이하  2020   2    3962
4503  제주  전용면적 85㎡초과 102㎡이하  2020   2     NaN
4504  제주        전용면적 102㎡초과  2020   2    3601

[4505 rows x 5 columns]

column의 이름을 재정의

In [6]:
df = df.rename(columns={'분양가격(㎡)': '분양가격'})
df

     지역명               규모구분    연도   월  분양가격
0     서울                 전체  2015  10  5841
1     서울         전용면적 60㎡이하  2015  10  5652
2     서울   전용면적 60㎡초과 85㎡이하  2015  10  5882
3     서울  전용면적 85㎡초과 102㎡이하  2015  10  5721
4     서울        전용면적 102㎡초과  2015  10  5879
...   ..                ...   ...  ..   ...
4500  제주                 전체  2020   2  3955
4501  제주         전용면적 60㎡이하  2020   2  4039
4502  제주   전용면적 60㎡초과 85㎡이하  2020   2  3962
4503  제주  전용면적 85㎡초과 102㎡이하  2020   2   NaN
4504  제주        전용면적 102㎡초과  2020   2  3601

[4505 rows x 5 columns]

### 빈 값과 Data Type 확인하기

In [7]:
# 코드를 입력해 주세요

### 통계값 확인

In [8]:
# 코드를 입력해 주세요

### 전처리 실전 연습 : 분양가격 column을 int 타입으로 변환

In [9]:
df['분양가격'].astype(int)

ValueError: ignored

### 데이터 공백없애기

[tip] column의 문자열에 strip을 실행하고자 할 때는 str.strip()를 실행해줘야 합니다

[예시] df['분양가격'].str.strip()

In [ ]:
df.loc[df['분양가격'] == '  ']

In [ ]:
# 코드를 입력해 주세요

In [ ]:
df.loc[df['분양가격'] == '']

### 빈 공백이 있는 데이터는 0을 넣어주세요

In [ ]:
# 코드를 입력해 주세요

In [ ]:
df['분양가격'].astype(int)

### NaN 값은 fillna로 채워 주도록 합시다!

In [ ]:
# 코드를 입력해 주세요

In [ ]:
df['분양가격'].astype(int)

In [ ]:
df.loc[df['분양가격'] == '6,657']

### "," 제거

In [ ]:
# 코드

In [ ]:
df.iloc[2125]

In [ ]:
df['분양가격'].astype(int)

In [ ]:
# 코드를 입력해 주세요

In [ ]:
df['분양가격'].astype(int)

### - 제거하기

In [ ]:
# 코드를 입력해 주세요

In [ ]:
df['분양가격'].astype(int)

### NaN 값은 0으로 채워 줍시다

In [ ]:
# 코드를 입력해 주세요

In [ ]:
df['분양가격'].astype(int)

In [ ]:
df.loc[df['분양가격'] == '']

### 빈 값은 0으로 채워주기

In [ ]:
# 코드를 입력해 주세요

In [ ]:
df['분양가격'] = df['분양가격'].astype(int)

### 분양가격 다시확인

In [ ]:
df.info()

### 지역별 평균 분양가격을 확인해 봅시다

In [ ]:
# 코드를 입력해 주세요

###분양가격이 100보다 작은 행은 제거하기

In [ ]:
df.loc[ df['지역명'] == 0]

In [ ]:
## 코드 (index 가져오기)

In [ ]:
## 코드 (index를 행 기준으로 drop)

다시 한 번 지역명으로 분양가격을 확인해 보겠습니다.

In [ ]:
## 코드

count()로 데이터의 갯수도 확인해 볼까요?

In [ ]:
## 코드

지역 별 가장 비싼 분양가는 어떻게 될까요?

In [ ]:
## 코드

### 연도별로 분양가격을 확인해 봅시다.

In [ ]:
## 코드

## 피벗 테이블을 활용해서 볼까요?

* 행인덱스: 연도
* 열인덱스: 규모구분
* 값: 분양가

In [ ]:
## 코드

## 연도별, 규모별 가격을 알아볼까요?

In [ ]:
## 코드

In [ ]:
## 코드 : pd.DataFrame()으로 한 번 더 감싸주기